### ISSUE TITLE
Published npm module contains index.tsx when it should contain index.js

### ISSUE THREAD

**Issue by yoDon** [baughmann/react-use-queue#1]
Looks like the wrong files were published to npm.

Trying to `import useQueue from "react-use-queue"` in a create-react-app typescript project after `npm install react-use-queue` results in an error:

```
Failed to compile.

./node_modules/react-use-queue/index.tsx 9:7
Module parse failed: Unexpected token (9:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @description A wrapper around a task to be performed
|  */
> export interface Job {
|   /**
|    * @description A task to be performed. It must return `void` or a `Promise<void>`
```

**Comment by baughmann** [comment]
@yoDon Sorry, my first published NPM package. Indeed, the first time making one that isn't referenced in the local FS. Not sure why I wasn't getting this error in React Native...

Go ahead and give `0.1.2` a try and let me know.

**Comment by yoDon** [comment]
Looks good - 0.1.2 is installing and building successfully - on to trying something useful with it :)

**Comment by baughmann** [comment]
@yoDon copy that, thanks for reporting this!
