### ISSUE TITLE
Problems with Webpack Loaders in Next.js

### ISSUE THREAD

**Issue by Sr-santi** [baughmann/react-use-queue#3]
Hi, I'm using this package in a next.js application.
I want to use this solution to make sequential processing as in the following example:
![queue-processing](https://user-images.githubusercontent.com/67811126/159339248-cf196e28-62a6-4c64-b1d9-dede902c8e31.gif)
this is an example of [ember-concurrency](http://ember-concurrency.com/docs/task-concurrency/).

this is my implementation, `markComplete` is an async function and returns void.

```
import useQueue from "react-use-queue"

export default function Open({...}) {

    const addProcessingToQueue = () => {
        Queue.addJob({
            task: () => markComplete(parameters),
        })
    }

    return(
        ProcessingChecklist
            ....
            markComplete={addProcessingToQueue}
            ...
          />
    )
}
```
I have this problem when I try to run my project:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/67811126/159340666-1d4699a8-3caf-48a7-b88d-7b76948b1cbc.png">

**Comment by baughmann** [comment]
@Sr-santi Sorry I must have missed the email this generated or something. I will take a look when I can (hopefully tomorrow night) and try to reproduce your problems.

**Comment by baughmann** [comment]
@Sr-santi Finally got around to fixing this. Is your use case using typescript?

**Comment by baughmann** [comment]
I *believe* the issue stems from the lib not having plain ole JS support. I've added it as of `0.5.0`. Try it and let me know.

**Comment by baughmann** [comment]
@Sr-santi Closing this for now, but please try 0.5.0 when you can and let me know if this is still an issue for you.
